/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import chat.ChatInterface;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * Primera vista de la interfaz grafica. de aqui se puede entrar a la pestaña de servidor para crear uno
 * O conectarse al servidor.
 * @author Usuario
 */
public class WelcomeView extends javax.swing.JPanel {
    JFrame frame;
    /**
     * Crea la nueva forma WelcomeView
     * @param frame: Recibe el JFrame de donde fue creado.
     */
    public WelcomeView(JFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createServerButton = new javax.swing.JButton();
        IpNumber = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterChatBurron = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ErrorMessage = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createServerButton.setText("Pestaña de servidor");
        createServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createServerButtonActionPerformed(evt);
            }
        });
        add(createServerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, -1));

        IpNumber.setText("localhost");
        IpNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpNumberActionPerformed(evt);
            }
        });
        add(IpNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, -1));

        nameField.setText("Nombre");
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("IP:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 99, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 48)); // NOI18N
        jLabel3.setText("JAVA RMI");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 43));

        enterChatBurron.setText("Conectarse como cliente");
        enterChatBurron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterChatBurronActionPerformed(evt);
            }
        });
        add(enterChatBurron, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 110, 70));

        ErrorMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(255, 255, 255));
        add(ErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 170, 40));

        portTextField.setText("port");
        portTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portTextFieldActionPerformed(evt);
            }
        });
        add(portTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 170, -1));

        jLabel4.setText("Port:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 99, -1));

        jPasswordField1.setText("jPasswordField1");
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, -1));

        jLabel5.setText("Contraseña");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void IpNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpNumberActionPerformed

    private void createServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createServerButtonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(new ServerView(frame));
    }//GEN-LAST:event_createServerButtonActionPerformed

    private void enterChatBurronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterChatBurronActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {        
            int port = Integer.parseInt(portTextField.getText());
            Registry registry = LocateRegistry.getRegistry(IpNumber.getText(), port);
            ChatInterface chat = (ChatInterface)registry.lookup("chatServer");  //getting a remote reference       
            frame.getContentPane().removeAll();
            frame.getContentPane().add(new ChatClientView(frame,chat,nameField.getText(),IpNumber.getText(),port));
        } catch (Exception e) {
           this.setVisible(true);
           this.ErrorMessage.setText("Error de conexion");
           e.printStackTrace();
        }        
        
    }//GEN-LAST:event_enterChatBurronActionPerformed

    private void portTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JTextField IpNumber;
    private javax.swing.JButton createServerButton;
    private javax.swing.JButton enterChatBurron;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField portTextField;
    // End of variables declaration//GEN-END:variables
}
