/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import chat.ChatInterface;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class WelcomeView extends javax.swing.JPanel {
    JFrame frame;
    /**
     * Creates new form WelcomeView
     * @param frame
     */
    public WelcomeView(JFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createServerButton = new javax.swing.JButton();
        IpNumber = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterChatBurron = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ErrorMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createServerButton.setText("Crear Servidor");
        createServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createServerButtonActionPerformed(evt);
            }
        });
        add(createServerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 130, -1));

        IpNumber.setText("localhost");
        IpNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpNumberActionPerformed(evt);
            }
        });
        add(IpNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));

        nameField.setText("Nombre");
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 118, -1, -1));

        jLabel2.setText("IP");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 207, 99, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 48)); // NOI18N
        jLabel3.setText("JAVA RMI");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 43));

        enterChatBurron.setText("Entrar a un chat");
        enterChatBurron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterChatBurronActionPerformed(evt);
            }
        });
        add(enterChatBurron, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 110, 70));

        ErrorMessage.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        add(ErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void IpNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpNumberActionPerformed

    private void createServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createServerButtonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(new ServerView(frame));
    }//GEN-LAST:event_createServerButtonActionPerformed

    private void enterChatBurronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterChatBurronActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {        
            Registry registry = LocateRegistry.getRegistry(IpNumber.getText(), 2000);
            ChatInterface chat = (ChatInterface)registry.lookup("chatServer");  //getting a remote reference       
            frame.getContentPane().removeAll();
            frame.getContentPane().add(new ChatClientView(frame,chat,nameField.getText()));
        } catch (Exception e) {
           this.setVisible(true);
           this.ErrorMessage.setText("Error de conexion");
           e.printStackTrace();
        }        
        
    }//GEN-LAST:event_enterChatBurronActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JTextField IpNumber;
    private javax.swing.JButton createServerButton;
    private javax.swing.JButton enterChatBurron;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
