/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package remote.desktopview;

import java.awt.Graphics2D;
import java.io.ByteArrayInputStream;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import remote.desktop.IRemoteDesktop;
/**
 *
 * @author Usuario
 */
public class DesktopView extends javax.swing.JPanel {

    /**
     * Creates new form desktopView
     */
    private IRemoteDesktop remote_obj;
    private String quality;
    private JFrame frame;
    public DesktopView(IRemoteDesktop remote_obj, JFrame frame) {
        try {
            initComponents();
            frame.setSize(600,400);
            this.remote_obj = remote_obj;
            this.frame = frame;
            quality = "low";
            run();
            execute();      
        } catch (Exception ex) {
            Logger.getLogger(DesktopView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void execute(){
        Thread t1 = new Thread(() -> {
            while (true) {
                              // this thread is used to refresh the chat window by every second
                try {   //Da la pantallas
                    run();    
                    //Thread.sleep(0);
                } catch (InterruptedException ex) {
                    Logger.getLogger(DesktopView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(DesktopView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screen_label = new javax.swing.JLabel();

        screen_label.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(screen_label)
                .addGap(0, 759, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(screen_label)
                .addGap(0, 463, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    BufferedImage resizeImage(BufferedImage originalImage, int targetWidth, int targetHeight) throws IOException {
        BufferedImage resizedImage = new BufferedImage(targetWidth, targetHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = resizedImage.createGraphics();
        graphics2D.drawImage(originalImage, 0, 0, targetWidth, targetHeight, null);
        graphics2D.dispose();
        return resizedImage;
    }
    private void run () throws Exception{
        byte[] dgram;
        dgram = this.remote_obj.takeScreenshotServer(quality);        
        ByteArrayInputStream bis = new ByteArrayInputStream(dgram);
        //System.out.print(bis);
        
        BufferedImage screenshot = ImageIO.read(bis);
        screenshot = resizeImage(screenshot, frame.getWidth(), frame.getHeight());

        //this.screen_label.setText(quality);
        this.screen_label.setIcon(new ImageIcon(screenshot));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel screen_label;
    // End of variables declaration//GEN-END:variables
}
